services:
  mysql-db:
    image: mysql:8.0
    container_name: petclinic-db
    restart: always
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: petuser
      MYSQL_PASSWORD: petpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: petclinic-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
